//! Sync a game directory against an MHF patch server.
//!
//! This is the update mechanism the original launcher (`mhl.dll`) uses,
//! reimplemented so that mhf-outpost / mhf-iel users get the same per-file
//! updates without IE. The server side is the ZeruLight "MHF Patch Server API"
//! layout (a `mhfdat/{exe,dat}` tree plus a CRC32 manifest generated by
//! `genMhfKey.py`), which Erupe advertises to clients as `patchServer`.
//!
//! Request shapes, recovered from `mhl.dll`:
//!
//! ```text
//! GET http://<host>/mhf_file.php?key=<n>        -> manifest ("MHFUP_00.DAT")
//! GET http://<host>/mhfdat/<exe|dat>/<file>?id=<n>
//! ```
//!
//! Manifest lines are `CRC32,FILETIME_LO,FILETIME_HI,PATH,SIZE,FLAG` with
//! backslash paths rooted at `exe\` (game root) or `dat\`. Zero-byte files are
//! never listed, so a fresh install must get its placeholders elsewhere.
//!
//! Like the original launcher, files are compared by size then CRC32; files
//! present locally but absent from the manifest are left alone.

use anyhow::{bail, Context, Result};
use indicatif::{ProgressBar, ProgressStyle};
use rayon::prelude::*;
use std::fs::{self, File};
use std::io::{Read, Write};
use std::path::{Component, Path, PathBuf};
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::Arc;
use std::time::Duration;

const CONNECT_TIMEOUT: Duration = Duration::from_secs(30);
const REQUEST_TIMEOUT: Duration = Duration::from_secs(600);
const CHUNK: usize = 64 * 1024;
const DOWNLOAD_RETRIES: usize = 3;
/// The original launcher identifies itself as "mhfhttp" for file requests.
const USER_AGENT: &str = "mhf-outpost/0.1 (mhfhttp)";

/// Progress callback: `(phase, done, total)` where `phase` is "check" (files)
/// or "download" (bytes). When set, the indicatif bars are suppressed.
pub type ProgressCallback = Arc<dyn Fn(&str, u64, u64) + Send + Sync>;

// ── Manifest ─────────────────────────────────────────────────────────────────

/// One line of the patch manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PatchEntry {
    /// Path as the server spells it (`exe\mhf.exe`, `dat\mhfdat.bin`).
    pub server_path: String,
    /// Path relative to the game root (`mhf.exe`, `dat/mhfdat.bin`).
    pub local_path: PathBuf,
    pub crc32: u32,
    pub size: u64,
}

/// Parse a `key.txt` / `MHFUP_00.DAT` manifest.
///
/// Malformed lines are an error rather than skipped: a truncated manifest
/// must not silently turn into "everything is up to date".
pub fn parse_manifest(text: &str) -> Result<Vec<PatchEntry>> {
    let mut entries = Vec::new();
    for (n, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split(',').collect();
        if f.len() != 6 {
            bail!("manifest line {}: expected 6 fields, got {}", n + 1, f.len());
        }
        let crc32 = u32::from_str_radix(f[0], 16)
            .with_context(|| format!("manifest line {}: bad CRC '{}'", n + 1, f[0]))?;
        let size: u64 = f[4]
            .parse()
            .with_context(|| format!("manifest line {}: bad size '{}'", n + 1, f[4]))?;
        let local_path = local_path_for(f[3])
            .with_context(|| format!("manifest line {}: bad path '{}'", n + 1, f[3]))?;
        entries.push(PatchEntry {
            server_path: f[3].to_string(),
            local_path,
            crc32,
            size,
        });
    }
    Ok(entries)
}

/// Map a manifest path to a path under the game root.
///
/// `exe\` entries live at the root, `dat\` entries keep their folder. Anything
/// that could escape the game directory is rejected.
fn local_path_for(server_path: &str) -> Result<PathBuf> {
    let unix = server_path.replace('\\', "/");
    let (prefix, rest) = unix
        .split_once('/')
        .ok_or_else(|| anyhow::anyhow!("no folder prefix"))?;
    let rel = match prefix {
        "exe" => PathBuf::from(rest),
        "dat" => PathBuf::from("dat").join(rest),
        other => bail!("unknown top-level folder '{other}'"),
    };
    if rest.is_empty() {
        bail!("empty file name");
    }
    for c in rel.components() {
        match c {
            Component::Normal(_) => {}
            _ => bail!("path escapes the game directory"),
        }
    }
    Ok(rel)
}

/// URL of a file in the `mhfdat/` tree.
fn file_url(base: &str, server_path: &str) -> String {
    format!(
        "{}/mhfdat/{}?id=0",
        base.trim_end_matches('/'),
        server_path.replace('\\', "/")
    )
}

/// Normalise a `patchServer` value into a base URL.
///
/// Erupe hands the original launcher a bare host (it prepends `http://`
/// itself); `API.PatchServer` may carry a scheme. Accept both.
pub fn base_url(patch_server: &str) -> Result<String> {
    let s = patch_server.trim().trim_end_matches('/');
    if s.is_empty() {
        bail!("this server does not advertise a patch server");
    }
    if s.starts_with("http://") || s.starts_with("https://") {
        Ok(s.to_string())
    } else {
        Ok(format!("http://{s}"))
    }
}

// ── Plan ─────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    Missing,
    SizeMismatch,
    CrcMismatch,
}

#[derive(Debug, Clone)]
pub struct Planned {
    pub entry: PatchEntry,
    pub reason: Reason,
}

#[derive(Debug, Default)]
pub struct SyncPlan {
    pub checked: usize,
    pub up_to_date: usize,
    pub to_download: Vec<Planned>,
}

impl SyncPlan {
    pub fn bytes_to_download(&self) -> u64 {
        self.to_download.iter().map(|p| p.entry.size).sum()
    }
}

/// Compare the game directory against the manifest.
///
/// Size is checked first (cheap); the CRC32 is only computed when sizes
/// match, which is what makes a no-op sync fast enough to run at every
/// launch. Files are hashed in parallel.
pub fn plan(root: &Path, entries: &[PatchEntry], on_progress: Option<&ProgressCallback>) -> SyncPlan {
    let total = entries.len() as u64;
    let done = AtomicU64::new(0);
    let pb = if on_progress.is_none() {
        let bar = ProgressBar::new(total);
        bar.set_style(
            ProgressStyle::with_template("{spinner:.cyan} [{bar:40.cyan/blue}] {pos}/{len} files checked")
                .unwrap()
                .progress_chars("=>-"),
        );
        Some(bar)
    } else {
        None
    };

    let results: Vec<Option<Planned>> = entries
        .par_iter()
        .map(|e| {
            let r = check_one(root, e);
            let n = done.fetch_add(1, Ordering::Relaxed) + 1;
            if let Some(bar) = &pb {
                bar.set_position(n);
            }
            if let Some(cb) = on_progress {
                cb("check", n, total);
            }
            r
        })
        .collect();
    if let Some(bar) = pb {
        bar.finish_and_clear();
    }

    let to_download: Vec<Planned> = results.into_iter().flatten().collect();
    SyncPlan {
        checked: entries.len(),
        up_to_date: entries.len() - to_download.len(),
        to_download,
    }
}

fn check_one(root: &Path, e: &PatchEntry) -> Option<Planned> {
    let path = root.join(&e.local_path);
    let meta = match fs::metadata(&path) {
        Ok(m) => m,
        Err(_) => return Some(Planned { entry: e.clone(), reason: Reason::Missing }),
    };
    if meta.len() != e.size {
        return Some(Planned { entry: e.clone(), reason: Reason::SizeMismatch });
    }
    match crc32_file(&path) {
        Ok(c) if c == e.crc32 => None,
        _ => Some(Planned { entry: e.clone(), reason: Reason::CrcMismatch }),
    }
}

pub fn crc32_file(path: &Path) -> std::io::Result<u32> {
    let mut f = File::open(path)?;
    let mut h = crc32fast::Hasher::new();
    let mut buf = vec![0u8; CHUNK];
    loop {
        let n = f.read(&mut buf)?;
        if n == 0 {
            break;
        }
        h.update(&buf[..n]);
    }
    Ok(h.finalize())
}

// ── Apply ────────────────────────────────────────────────────────────────────

#[derive(Debug, Default)]
pub struct SyncReport {
    pub checked: usize,
    pub up_to_date: usize,
    pub downloaded: usize,
    pub bytes_downloaded: u64,
}

pub struct SyncOptions {
    /// Game root directory (contains or will contain mhf.exe, dat/, …).
    pub dest: PathBuf,
    /// `patchServer` value from Erupe, or a full base URL.
    pub patch_server: String,
    /// Only report what would be downloaded.
    pub dry_run: bool,
    /// Progress callback; suppresses the indicatif bars when set.
    pub on_progress: Option<ProgressCallback>,
}

/// Fetch the manifest, compare, download what differs.
pub fn run(opts: SyncOptions) -> Result<SyncReport> {
    let base = base_url(&opts.patch_server)?;
    let client = reqwest::blocking::Client::builder()
        .user_agent(USER_AGENT)
        .connect_timeout(CONNECT_TIMEOUT)
        .timeout(REQUEST_TIMEOUT)
        .build()?;

    println!("Patch server: {base}");
    let entries = fetch_manifest(&client, &base)?;
    println!("Manifest: {} file(s)", entries.len());

    fs::create_dir_all(&opts.dest)
        .with_context(|| format!("cannot create '{}'", opts.dest.display()))?;

    let plan = plan(&opts.dest, &entries, opts.on_progress.as_ref());
    let mut report = SyncReport {
        checked: plan.checked,
        up_to_date: plan.up_to_date,
        ..Default::default()
    };

    if plan.to_download.is_empty() {
        println!("✓ All {} file(s) up to date", plan.checked);
        return Ok(report);
    }

    let total_bytes = plan.bytes_to_download();
    println!(
        "{} file(s) to download ({:.1} MiB)",
        plan.to_download.len(),
        total_bytes as f64 / 1_048_576.0
    );
    if opts.dry_run {
        for p in &plan.to_download {
            println!("  {:?} {}", p.reason, p.entry.local_path.display());
        }
        return Ok(report);
    }

    let pb = if opts.on_progress.is_none() {
        let bar = ProgressBar::new(total_bytes);
        bar.set_style(
            ProgressStyle::with_template(
                "{spinner:.cyan} [{bar:40.cyan/blue}] {bytes}/{total_bytes} ({binary_bytes_per_sec}, {eta}) {wide_msg}",
            )
            .unwrap()
            .progress_chars("=>-"),
        );
        Some(bar)
    } else {
        None
    };

    let done_bytes = AtomicU64::new(0);
    let done_files = AtomicUsize::new(0);
    let on_progress = opts.on_progress.clone();

    // A handful of parallel connections: fast on a 5 GB first install, gentle
    // on the server.
    let pool = rayon::ThreadPoolBuilder::new().num_threads(4).build()?;
    let results: Vec<Result<()>> = pool.install(|| {
        plan.to_download
            .par_iter()
            .map(|p| {
                if let Some(bar) = &pb {
                    bar.set_message(p.entry.local_path.display().to_string());
                }
                let r = download_entry(&client, &base, &opts.dest, &p.entry);
                if r.is_ok() {
                    let b = done_bytes.fetch_add(p.entry.size, Ordering::Relaxed) + p.entry.size;
                    done_files.fetch_add(1, Ordering::Relaxed);
                    if let Some(bar) = &pb {
                        bar.set_position(b);
                    }
                    if let Some(cb) = &on_progress {
                        cb("download", b, total_bytes);
                    }
                }
                r.with_context(|| format!("{}", p.entry.local_path.display()))
            })
            .collect()
    });
    if let Some(bar) = pb {
        bar.finish_and_clear();
    }

    report.downloaded = done_files.load(Ordering::Relaxed);
    report.bytes_downloaded = done_bytes.load(Ordering::Relaxed);

    let failures: Vec<String> = results
        .into_iter()
        .filter_map(|r| r.err().map(|e| format!("{e:#}")))
        .collect();
    if !failures.is_empty() {
        bail!(
            "{} of {} download(s) failed (run again to retry):\n  {}",
            failures.len(),
            plan.to_download.len(),
            failures.join("\n  ")
        );
    }

    println!(
        "✓ Downloaded {} file(s), {:.1} MiB; {} already up to date",
        report.downloaded,
        report.bytes_downloaded as f64 / 1_048_576.0,
        report.up_to_date
    );
    Ok(report)
}

pub fn fetch_manifest(client: &reqwest::blocking::Client, base: &str) -> Result<Vec<PatchEntry>> {
    let url = format!("{}/mhf_file.php?key=0", base.trim_end_matches('/'));
    let resp = client
        .get(&url)
        .send()
        .with_context(|| format!("failed to connect to {url}"))?;
    if !resp.status().is_success() {
        bail!("patch server returned {} for the manifest", resp.status());
    }
    let text = resp.text().context("failed to read manifest")?;
    let entries = parse_manifest(&text)?;
    if entries.is_empty() {
        bail!("patch server returned an empty manifest");
    }
    Ok(entries)
}

/// Download one file to `<path>.part`, verify size and CRC32, then rename
/// over the old file. A failed attempt leaves nothing half-written in place.
fn download_entry(
    client: &reqwest::blocking::Client,
    base: &str,
    root: &Path,
    e: &PatchEntry,
) -> Result<()> {
    let dest = root.join(&e.local_path);
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent)?;
    }
    let part = dest.with_extension(match dest.extension() {
        Some(ext) => format!("{}.part", ext.to_string_lossy()),
        None => "part".to_string(),
    });
    let url = file_url(base, &e.server_path);

    let mut last_err = None;
    for attempt in 1..=DOWNLOAD_RETRIES {
        match fetch_to(client, &url, &part, e) {
            Ok(()) => {
                fs::rename(&part, &dest)
                    .with_context(|| format!("cannot replace '{}'", dest.display()))?;
                return Ok(());
            }
            Err(err) => {
                let _ = fs::remove_file(&part);
                last_err = Some(err);
                if attempt < DOWNLOAD_RETRIES {
                    std::thread::sleep(Duration::from_secs(2 * attempt as u64));
                }
            }
        }
    }
    Err(last_err.unwrap())
}

fn fetch_to(client: &reqwest::blocking::Client, url: &str, part: &Path, e: &PatchEntry) -> Result<()> {
    let mut resp = client.get(url).send().with_context(|| format!("GET {url}"))?;
    if !resp.status().is_success() {
        bail!("server returned {} for {url}", resp.status());
    }
    let mut file = File::create(part)?;
    let mut hasher = crc32fast::Hasher::new();
    let mut written = 0u64;
    let mut buf = vec![0u8; CHUNK];
    loop {
        let n = resp.read(&mut buf)?;
        if n == 0 {
            break;
        }
        file.write_all(&buf[..n])?;
        hasher.update(&buf[..n]);
        written += n as u64;
    }
    file.flush()?;
    if written != e.size {
        bail!("size mismatch: expected {} B, got {} B", e.size, written);
    }
    let crc = hasher.finalize();
    if crc != e.crc32 {
        bail!("CRC32 mismatch: expected {:08X}, got {:08X}", e.crc32, crc);
    }
    Ok(())
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    const LINE_EXE: &str = "28B2BB6C,CDF6C300,01DA01F4,exe\\mhf.exe,944624,0";
    const LINE_DAT: &str = "A4E501E6,EF0AE400,01DA01F3,dat\\npc\\npc10.bin,7383160,0";

    #[test]
    fn parses_manifest_lines() {
        let text = format!("{LINE_EXE}\n{LINE_DAT}\n\n");
        let m = parse_manifest(&text).unwrap();
        assert_eq!(m.len(), 2);
        assert_eq!(m[0].crc32, 0x28B2BB6C);
        assert_eq!(m[0].size, 944624);
        assert_eq!(m[0].local_path, PathBuf::from("mhf.exe"));
        assert_eq!(m[1].local_path, PathBuf::from("dat/npc/npc10.bin"));
        assert_eq!(m[1].server_path, "dat\\npc\\npc10.bin");
    }

    #[test]
    fn rejects_malformed_lines() {
        assert!(parse_manifest("not,a,manifest").is_err());
        assert!(parse_manifest("ZZZZ,0,0,exe\\a,1,0").is_err());
        assert!(parse_manifest("0,0,0,exe\\a,big,0").is_err());
    }

    #[test]
    fn rejects_escaping_paths() {
        assert!(local_path_for("exe\\..\\evil.dll").is_err());
        assert!(local_path_for("dat\\..\\..\\x").is_err());
        assert!(local_path_for("C:\\Windows\\x").is_err());
        assert!(local_path_for("bin\\x").is_err());
        assert!(local_path_for("exe\\").is_err());
        assert!(local_path_for("mhf.exe").is_err());
    }

    #[test]
    fn builds_urls() {
        assert_eq!(
            file_url("http://h", "dat\\a\\b.bin"),
            "http://h/mhfdat/dat/a/b.bin?id=0"
        );
        assert_eq!(base_url("frontier.mogapedia.fr").unwrap(), "http://frontier.mogapedia.fr");
        assert_eq!(base_url("https://x/").unwrap(), "https://x");
        assert!(base_url("  ").is_err());
    }

    #[test]
    fn plan_detects_missing_size_and_crc() {
        let dir = tempdir();
        std::fs::create_dir_all(dir.join("dat")).unwrap();
        std::fs::write(dir.join("ok.bin"), b"hello").unwrap();
        std::fs::write(dir.join("dat/wrong.bin"), b"hellO").unwrap();
        std::fs::write(dir.join("short.bin"), b"hi").unwrap();
        let crc_hello = crc32fast::hash(b"hello");
        let entries = vec![
            entry("exe\\ok.bin", crc_hello, 5),
            entry("dat\\wrong.bin", crc_hello, 5),
            entry("exe\\short.bin", crc_hello, 5),
            entry("exe\\missing.bin", crc_hello, 5),
        ];
        let p = plan(&dir, &entries, None);
        assert_eq!(p.checked, 4);
        assert_eq!(p.up_to_date, 1);
        let by_name: std::collections::HashMap<_, _> = p
            .to_download
            .iter()
            .map(|x| (x.entry.local_path.to_string_lossy().to_string(), x.reason))
            .collect();
        assert_eq!(by_name["dat/wrong.bin"], Reason::CrcMismatch);
        assert_eq!(by_name["short.bin"], Reason::SizeMismatch);
        assert_eq!(by_name["missing.bin"], Reason::Missing);
        assert_eq!(p.bytes_to_download(), 15);
        std::fs::remove_dir_all(&dir).unwrap();
    }

    fn entry(server_path: &str, crc32: u32, size: u64) -> PatchEntry {
        PatchEntry {
            server_path: server_path.to_string(),
            local_path: local_path_for(server_path).unwrap(),
            crc32,
            size,
        }
    }

    fn tempdir() -> PathBuf {
        let d = std::env::temp_dir().join(format!(
            "mhf-outpost-sync-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&d).unwrap();
        d
    }
}
